### PR TITLE
Rename yarr to redcord

### PR DESCRIPTION
**Pull request by donaldong**
Unfortunately, the name `yarr` is also taken on RubyGems. So instead, I purpose us moving to a new namespace `redcord`.

### CODE REVIEW

**Comment by donaldong** [comment]
nits

:mag_right: [Click to see changes since last update](https://github.com/chanzuckerberg/redis-record/compare/28da1e8c4904f08050efcbe54bb555781d54b9bd..d330f7ac3273cdb55c4ab0fdcbd10898560eaf96).

**Comment by katyho** [comment]
> Unfortunately, the name yarr is also taken on RubyGems

😭 

Do you know how this gem will get discovered on https://rubygems.org/ then?

**Comment by donaldong** [comment]
> Do you know how this gem will get discovered on https://rubygems.org/ then?

I guess we need to find a different way to market this gem 😄 When we're ready, maybe we can write a post and share it with the rails developer community.

**Comment by manhhung741** [comment]
I think we should come up with a name not used in rubygems. Come up with something fun

**Comment by donaldong** [comment]
move to namespace redcord

:mag_right: [Click to see changes since last update](https://github.com/chanzuckerberg/redis-record/compare/2b34ec93f20d1f762431b6dfcdcd00c8ba10e845..8caca8cc255769f0fdf3da1b73d4d6be061b9738).

**Comment by donaldong** [comment]
redisrecord -> redcord

:mag_right: [Click to see changes since last update](https://github.com/chanzuckerberg/redis-record/compare/82bd5c1cc41c64292e25562c602a2721dfadaea2..06cafc781634e8e741e4398d94231afe34b4f449).

**Comment by donaldong** [comment]
update README.md

:mag_right: [Click to see changes since last update](https://github.com/chanzuckerberg/redis-record/compare/0079eee89c097bc87a0009d965b0686b99fe9e3e..49e8dc862c0733573cd70bbdddc7a1424a211e24).

**Comment by donaldong** [comment]
YARR -> Redcord

:mag_right: [Click to see changes since last update](https://github.com/chanzuckerberg/redis-record/compare/09201f336b259d7ca50cf0de79c0469661bac915..c76445df83bc950048056e99f28328970e20f2d8).

**Pull request merged**
